---

- name: Assertions
  ansible.builtin.assert:
    that:
      - ansible_distribution_major_version | int >= 8

- name: Import Microsoft GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Setup microsoft YUM repository
  ansible.builtin.dnf:
    name: https://packages.microsoft.com/config/rhel/{{ ansible_distribution_major_version }}/packages-microsoft-prod.rpm
    state: present
  when: ansible_distribution_major_version == '8'

- name: Setup microsoft YUM repository
  ansible.builtin.dnf:
    name: https://packages.microsoft.com/config/rhel/{{ ansible_distribution_major_version }}.0/packages-microsoft-prod.rpm
    state: present
  when: ansible_distribution_major_version == '9'

- name: Install azure-cli
  ansible.builtin.dnf:
    name: azure-cli
    state: present
