---

- name: Download APT signing key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: "0644"

- name: Convert APT key into binary format
  ansible.builtin.command:
    cmd: gpg --batch --yes --no-tty --dearmor -o /tmp/microsoft.gpg /tmp/microsoft.asc
  changed_when: false

- name: Import Microsoft GPG key
  ansible.builtin.apt_key:
    state: present
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
  become: yes
  when: ansible_distribution_major_version | int < 12

- name: Copy APT signing key into the proper drop-in directory
  ansible.builtin.copy:
    src: /tmp/microsoft.gpg
    dest: /etc/apt/trusted.gpg.d/microsoft.gpg
    remote_src: yes
    mode: "0644"
  when: ansible_distribution_major_version | int >= 12

- name: Setup Microsoft APT repository
  ansible.builtin.apt_repository:
    filename: microsoft
    repo: >-
      {%- if ansible_distribution_major_version | int < 12 -%}
      deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
      {%- else -%}
      deb [signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
      {%- endif -%}
    state: present
  become: yes

- name: Install azure-cli
  ansible.builtin.apt:
    name: azure-cli
    state: present
  become: yes
