---

- name: Import Microsoft GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: yes

- name: Download microsoft repository RPM
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/config/fedora/{{ ansible_distribution_major_version }}/packages-microsoft-prod.rpm
    dest: /tmp/packages-microsoft-prod.rpm

- name: Setup microsoft YUM repository
  ansible.builtin.dnf:
    name: /tmp/packages-microsoft-prod.rpm
    state: present
  become: yes

- name: Upgrade pyOpenSSL from pypi
  ansible.builtin.pip:
    name: "pyOpenSSL>22.1.0"
    state: present
  become: yes

- name: Install azure-cli
  ansible.builtin.dnf:
    name: azure-cli
    state: present
  become: yes
