---

- name: Install OS specific tasks
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.distribution }}.yml"
    - "family-{{ ansible_facts.os_family }}.yml"

- name: Install extensions
  ansible.builtin.include_tasks:
    file: extensions.yml
