---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    azure_cli_extensions: [{'name': 'aks-preview'}, {'name': 'ssh', 'system': True}, {'name': 'image-copy-extension', 'version': '0.2.12'}]
  tasks:
    - name: Include role 'ansible-role-azure_cli'
      ansible.builtin.include_role:
        name: ansible-role-azure_cli
